export function Footer() {
  return (
    <footer className="app-footer">
      <span>FUNNEL DUO · Vibe Coding Finance OS · v1.2.4</span>
      <span>
        Generated by <span className="gold">Claude Code</span> · MCP synced · Stripe / Supabase / Google Sheets
      </span>
      <span>Last sync 11:47:02 MYT · next refresh in 04:58</span>
    </footer>
  );
}
